// SPDX-License-Identifier: Apache-2.0
/**
 * Generate THIRD_PARTY_NOTICES.md from the web app's production dependency
 * tree (§9.1), plus the models, which aren't npm packages.
 *
 *   node tools/notices.ts           write THIRD_PARTY_NOTICES.md
 *   node tools/notices.ts --check   fail if it is out of date (CI)
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

interface Package {
	name: string;
	versions: string[];
	paths: string[];
	license: string;
	homepage?: string;
	author?: string;
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(root, 'THIRD_PARTY_NOTICES.md');
const LICENCE_FILE = /^(licen[cs]e|copying|notice)([.-].*)?$/i;

/** Licence texts in a package: top level, and one level down for bundled codecs (jSquash keeps them in codec/). */
function licenceTexts(dir: string): Array<{ file: string; text: string }> {
	const found: Array<{ file: string; text: string }> = [];
	const scan = (current: string, depth: number) => {
		for (const entry of readdirSync(current).sort()) {
			const full = path.join(current, entry);
			if (entry === 'node_modules') continue;
			const stat = statSync(full);
			if (stat.isDirectory() && depth < 1 && /^(codec|licenses?)$/i.test(entry)) scan(full, depth + 1);
			else if (stat.isFile() && LICENCE_FILE.test(entry)) {
				found.push({ file: path.relative(dir, full), text: readFileSync(full, 'utf8').trim() });
			}
		}
	};
	if (existsSync(dir)) scan(dir, 0);
	return found;
}

const NAFNET_MIT = `MIT License

Copyright (c) 2022 megvii-model

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

export function render(packages: Package[]): string {
	const lines = [
		'# Third-party notices',
		'',
		'Hush is licensed under the Apache License 2.0. Its build output also contains',
		'the third-party components below, under their own licences.',
		'',
		'This file is generated by `node tools/notices.ts` from the web app’s',
		'production dependencies; CI fails if it is out of date. Do not edit by hand.',
		'',
		'## Models',
		'',
		'### NAFNet (SIDD), ONNX conversions',
		'',
		'- Source: https://github.com/megvii-research/NAFNet (weights: the official SIDD checkpoints)',
		'- Paper: Chen, Chu, Zhang, Sun, “Simple Baselines for Image Restoration”, ECCV 2022',
		'- Training data: Smartphone Image Denoising Dataset (SIDD), MIT License — https://abdokamel.github.io/sidd/',
		'- Hush ships ONNX conversions of the PyTorch checkpoints (fp32, fp16 and int8 variants).',
		'',
		'```',
		NAFNET_MIT,
		'```',
		'',
		'## Packages',
		'',
		'| Package | Version | Licence |',
		'| --- | --- | --- |',
		...packages.map(
			(p) => `| ${p.homepage ? `[${p.name}](${p.homepage})` : p.name} | ${p.versions.join(', ')} | ${p.license} |`,
		),
		'',
	];
	for (const p of packages) {
		lines.push(`### ${p.name} ${p.versions.join(', ')}`, '', `Licence: ${p.license}`, '');
		const texts = licenceTexts(p.paths[0] ?? '');
		if (texts.length === 0) lines.push('_No licence file in the package; see its repository._', '');
		for (const { file, text } of texts) lines.push(`\`${file}\`:`, '', '```', text, '```', '');
	}
	return lines.join('\n');
}

function main(): void {
	const json = execFileSync('pnpm', ['licenses', 'list', '--prod', '--json', '--filter', '@hush/web'], {
		cwd: root,
		encoding: 'utf8',
		maxBuffer: 64 * 1024 * 1024,
	});
	const byLicence = JSON.parse(json) as Record<string, Package[]>;
	const packages = Object.values(byLicence)
		.flat()
		// Workspace packages are Hush itself; type declarations never reach the browser.
		.filter((p) => !p.name.startsWith('@hush/') && !p.name.startsWith('@types/'))
		.sort((a, b) => a.name.localeCompare(b.name));

	const text = render(packages);
	if (process.argv.includes('--check')) {
		const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
		if (current !== text) {
			console.error('THIRD_PARTY_NOTICES.md is out of date. Run `node tools/notices.ts` and commit the result.');
			process.exit(1);
		}
		console.log(`THIRD_PARTY_NOTICES.md is up to date (${packages.length} packages).`);
		return;
	}
	writeFileSync(target, text);
	console.log(`Wrote THIRD_PARTY_NOTICES.md (${packages.length} packages).`);
}

if (import.meta.main) main();
